In [2]:
printf('Hello, World!')

Hello, World!

In [3]:
2 + 5

ans = 7


In [4]:
7 * 9

ans = 63


In [5]:
a = 3.14

a = 3.1400


In [6]:
who

Variables visible from the current scope:

a    ans



In [7]:
whos

Variables visible from the current scope:

variables in scope: top scope

  Attr   Name        Size                     Bytes  Class
  ====   ====        ====                     =====  ===== 
         a           1x1                          8  double
         ans         1x1                          8  double

Total is 2 elements using 16 bytes



In [9]:
a = [1, 2, 3, 4, 5]

a =

   1   2   3   4   5



In [10]:
size(a)

ans =

   1   5



In [11]:
b = [1; 2; 3; 4; 5]
size(b)

b =

   1
   2
   3
   4
   5

ans =

   5   1



In [12]:
a(1)

ans = 1


In [13]:
ones(3, 3)

ans =

   1   1   1
   1   1   1
   1   1   1



In [ ]:
zeros(5, 5)

In [5]:
rand(4, 4)

ans =

   3.5227e-01   1.5708e-01   9.6104e-01   4.0963e-01
   8.4087e-01   1.1117e-01   5.5626e-03   2.3998e-01
   5.6306e-02   9.9298e-01   4.8409e-01   8.2713e-01
   4.7599e-01   2.3502e-01   1.7929e-01   1.6556e-01



In [16]:
logspace(1, 5, 5)

ans =

       10      100     1000    10000   100000



In [4]:
logspace(1, 5, 4)

ans =

   1.0000e+01   2.1544e+02   4.6416e+03   1.0000e+05



Linear Programming

In [12]:
%{
min f = -4a+b+7c
c = [-4, 1, 7]'

%}
c = [2; 3; -5]';
A = [1, 1, 1; 
    -2, 5, -1;
    1, 3, 1];
b = [7;-10;12]';
lb = [0, 0, 0];
%lower
ub = [];
%upper
ctype="SLU";
%{
F free
U <=
S =
L >=
D -3 <= 2a+4b+c <= 3
%}
vtype="CCC";
%{
C constant
I integer
%}
sense=1;
%{
sense=1 min f
sense=-1 max f
%}
param.itlim = 10000;

[xmin, fmin, status, extra]=glpk(c, A, b, lb, ub, ctype, vtype, sense, param);

